### ISSUE TITLE
Compatiblity with Cassandra-3.10

### ISSUE THREAD

**Issue by cindygl** [sebgiroux/Cassandra-Cluster-Admin#35]
I‘m trying to use this project to connect my remote cassandra-3.10 cluster but it report connection issue as
" ’An error occured while connecting to your Cassandra server: TSocket: Could not connect to 10.129.x.x:9160 (Connection refused [111])".

Does this project support Cassandra-3.10? Thanks.

**Comment by d4nyl0** [comment]
In Cassandra-3.11.4 default port is 9042; changing conf.inc.php with this parameter i get a page with only "Cassandra Cluster Admin" H1.
In Cassandra console I see:
INFO  [nioEventLoopGroup-2-8] 2019-03-27 14:49:31,378 Message.java:687 - Unexpected exception during request; channel = [id: 0x4e23ff46, L:/127.0.0.1:9042 - R:/127.0.0.1:59694]
java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_201]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_201]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_201]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:899) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:276) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]

Is it fixable? Can I do anything?

Thanks.
Danilo
